import { StyleSheet } from 'react-native';
import { Spacing, BorderRadius, Theme } from '@/constants/theme';

export const createStyles = (_theme: Theme, width: number) =>
  StyleSheet.create({
    scrollContent: {
      flexGrow: 1,
      backgroundColor: '#0b0907',
      paddingBottom: width >= 1100 ? Spacing.md : Spacing['5xl'],
    },
    heroSection: {
      overflow: 'hidden',
      paddingVertical: width >= 1100 ? 28 : 72,
      paddingHorizontal: Spacing['2xl'],
      alignItems: 'center',
      backgroundColor: '#120d09',
      borderBottomWidth: 1,
      borderBottomColor: 'rgba(173, 129, 66, 0.28)',
    },
    heroGlow: {
      position: 'absolute',
      top: -120,
      width: 320,
      height: 320,
      borderRadius: 999,
      backgroundColor: 'rgba(160, 78, 33, 0.18)',
    },
    heroDustLeft: {
      position: 'absolute',
      left: -24,
      top: 64,
      width: 120,
      height: 120,
      borderRadius: 999,
      backgroundColor: 'rgba(74, 45, 27, 0.25)',
    },
    heroDustRight: {
      position: 'absolute',
      right: -30,
      bottom: 48,
      width: 140,
      height: 140,
      borderRadius: 999,
      backgroundColor: 'rgba(117, 78, 38, 0.14)',
    },
    heroSubtitle: {
      fontSize: 11,
      letterSpacing: 7,
      textTransform: 'uppercase',
      fontWeight: '500',
      marginBottom: Spacing.md,
    },
    heroTitle: {
      fontSize: width >= 1100 ? 34 : 50,
      fontWeight: '300',
      textAlign: 'center',
      letterSpacing: 3,
    },
    heroDescription: {
      marginTop: width >= 1100 ? Spacing.sm : Spacing.lg,
      maxWidth: 420,
      textAlign: 'center',
      lineHeight: 22,
      letterSpacing: 0.4,
    },
    heroDivider: {
      width: 92,
      height: 1,
      backgroundColor: '#a57a45',
      marginTop: Spacing.xl,
    },
    heroSealRow: {
      marginTop: Spacing.lg,
      alignItems: 'center',
      gap: Spacing.sm,
    },
    heroSeal: {
      width: 42,
      height: 42,
      borderRadius: 21,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#87492d',
      borderWidth: 1,
      borderColor: '#d1a56a',
    },
    heroSealText: {
      letterSpacing: 2,
      textTransform: 'uppercase',
    },
    menuContainer: {
      paddingHorizontal: Spacing.xl,
      paddingTop: width >= 1100 ? Spacing.lg : Spacing.xl,
      gap: Spacing.lg,
      flexDirection: width >= 1100 ? 'row' : 'column',
      flexWrap: width >= 1100 ? 'wrap' : 'nowrap',
      alignContent: width >= 1100 ? 'flex-start' : 'stretch',
    },
    menuItemWrap: {
      borderRadius: BorderRadius.xl,
      width: width >= 1500 ? '31.8%' : width >= 1100 ? '48.5%' : '100%',
    },
    menuItem: {
      overflow: 'hidden',
      backgroundColor: '#16110c',
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: Spacing.xl,
      paddingVertical: width >= 1100 ? Spacing.md : Spacing.lg,
      borderWidth: 1,
      borderColor: 'rgba(155, 124, 73, 0.34)',
      borderRadius: BorderRadius.xl,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 14 },
      shadowOpacity: 0.28,
      shadowRadius: 28,
      elevation: 8,
    },
    menuEtching: {
      position: 'absolute',
      right: -16,
      top: -8,
      width: 110,
      height: 110,
      borderRadius: 999,
      backgroundColor: 'rgba(83, 61, 35, 0.12)',
      borderWidth: 1,
      borderColor: 'rgba(168, 135, 78, 0.1)',
    },
    menuIconContainer: {
      width: 58,
      height: 58,
      borderRadius: 16,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#0f0b08',
      marginRight: Spacing.lg,
      borderWidth: 1,
    },
    menuTextContainer: {
      flex: 1,
    },
    menuSubtitle: {
      marginTop: 6,
      letterSpacing: 0.4,
    },
    footer: {
      paddingHorizontal: Spacing.xl,
      paddingTop: width >= 1100 ? Spacing.md : Spacing['2xl'],
      alignItems: 'center',
    },
    footerText: {
      letterSpacing: 2,
      textTransform: 'uppercase',
    },
  });
