import { StyleSheet } from 'react-native';
import { Spacing, BorderRadius, Theme } from '@/constants/theme';

export const createStyles = (_theme: Theme) =>
  StyleSheet.create({
    scrollContent: {
      flexGrow: 1,
      paddingBottom: Spacing['5xl'],
      backgroundColor: '#0a0706',
      gap: Spacing.lg,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      gap: Spacing.md,
      backgroundColor: '#0a0706',
    },
    loadingText: {
      marginTop: Spacing.md,
    },
    headerSection: {
      overflow: 'hidden',
      backgroundColor: '#140f0b',
      paddingTop: Spacing['3xl'],
      paddingBottom: Spacing.xl,
      paddingHorizontal: Spacing.lg,
      borderBottomWidth: 1,
      borderBottomColor: 'rgba(176, 137, 81, 0.24)',
      gap: Spacing.md,
    },
    headerOverlay: {
      position: 'absolute',
      top: -90,
      alignSelf: 'center',
      width: 260,
      height: 260,
      borderRadius: 999,
      backgroundColor: 'rgba(145, 76, 37, 0.16)',
    },
    headerContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.lg,
    },
    backButton: {
      width: 42,
      height: 42,
      borderRadius: BorderRadius.lg,
      backgroundColor: '#221811',
      borderWidth: 1,
      borderColor: 'rgba(177, 136, 80, 0.2)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    headerTitleContainer: {
      flex: 1,
    },
    headerSubtitle: {
      textTransform: 'uppercase',
      letterSpacing: 2,
      marginBottom: 6,
    },
    headerTitle: {
      fontSize: 30,
      fontWeight: '300',
      letterSpacing: 1,
    },
    headerCopy: {
      lineHeight: 21,
      maxWidth: 540,
    },
    introSection: {
      paddingHorizontal: Spacing.lg,
    },
    introCard: {
      padding: Spacing.lg,
      borderRadius: BorderRadius['2xl'],
      borderWidth: 1,
      borderColor: 'rgba(167, 129, 76, 0.2)',
      backgroundColor: '#16100c',
      gap: Spacing.md,
    },
    introHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    introText: {
      lineHeight: 22,
    },
    stepsSection: {
      paddingHorizontal: Spacing.lg,
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: Spacing.md,
    },
    stepCard: {
      flex: 1,
      minWidth: 180,
      padding: Spacing.md,
      borderRadius: BorderRadius.xl,
      backgroundColor: '#100c09',
      borderWidth: 1,
      borderColor: 'rgba(160, 124, 74, 0.16)',
      gap: Spacing.sm,
    },
    stepIcon: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#1c130d',
      borderWidth: 1,
      borderColor: 'rgba(172, 133, 77, 0.18)',
    },
    stepCopy: {
      lineHeight: 19,
    },
    chapterPanel: {
      marginHorizontal: Spacing.lg,
      padding: Spacing.xl,
      borderRadius: BorderRadius['2xl'],
      backgroundColor: '#17110d',
      borderWidth: 1,
      borderColor: 'rgba(175, 137, 81, 0.24)',
      gap: Spacing.md,
    },
    chapterPanelHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: Spacing.md,
    },
    chapterPanelLabel: {
      textTransform: 'uppercase',
      letterSpacing: 3,
      marginBottom: 4,
    },
    chapterBadge: {
      paddingHorizontal: Spacing.sm,
      paddingVertical: 6,
      borderRadius: BorderRadius.full,
      backgroundColor: '#d7b26d',
    },
    chapterPanelCopy: {
      lineHeight: 21,
    },
    levelCard: {
      padding: Spacing.md,
      borderRadius: BorderRadius.xl,
      backgroundColor: '#0f0b08',
      borderWidth: 1,
      borderColor: 'rgba(163, 126, 76, 0.16)',
      gap: Spacing.md,
    },
    levelHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: Spacing.md,
    },
    enemyBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: Spacing.sm,
      paddingVertical: 5,
      borderRadius: BorderRadius.full,
      backgroundColor: '#1b130d',
      borderWidth: 1,
      borderColor: 'rgba(175, 136, 80, 0.16)',
    },
    levelText: {
      lineHeight: 20,
    },
    levelFactRow: {
      flexDirection: 'row',
      gap: Spacing.sm,
      flexWrap: 'wrap',
    },
    levelFact: {
      flex: 1,
      minWidth: 160,
      padding: Spacing.md,
      borderRadius: BorderRadius.lg,
      backgroundColor: '#18120d',
      borderWidth: 1,
      borderColor: 'rgba(161, 125, 74, 0.14)',
      gap: 4,
    },
    levelActions: {
      flexDirection: 'row',
      gap: Spacing.sm,
      flexWrap: 'wrap',
    },
    secondaryButton: {
      flex: 1,
      minWidth: 170,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: Spacing.xs,
      paddingVertical: Spacing.md,
      borderRadius: BorderRadius.full,
      backgroundColor: '#2a1d13',
      borderWidth: 1,
      borderColor: 'rgba(171, 132, 78, 0.22)',
    },
    primaryButton: {
      flex: 1,
      minWidth: 170,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: Spacing.xs,
      paddingVertical: Spacing.md,
      borderRadius: BorderRadius.full,
      backgroundColor: '#d7b26d',
      borderWidth: 1,
      borderColor: '#efd09b',
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(1, 1, 1, 0.74)',
      justifyContent: 'center',
      padding: Spacing.lg,
    },
    modalCard: {
      maxHeight: '84%',
      backgroundColor: '#16100c',
      borderRadius: BorderRadius['2xl'],
      borderWidth: 1,
      borderColor: 'rgba(175, 136, 79, 0.24)',
      overflow: 'hidden',
    },
    modalHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: Spacing.lg,
      borderBottomWidth: 1,
      borderBottomColor: 'rgba(162, 126, 76, 0.14)',
    },
    modalClose: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#221811',
    },
    modalBody: {
      padding: Spacing.lg,
    },
    modalStoryText: {
      lineHeight: 22,
    },
    modalFactCard: {
      marginTop: Spacing.lg,
      padding: Spacing.md,
      borderRadius: BorderRadius.xl,
      backgroundColor: '#100c09',
      borderWidth: 1,
      borderColor: 'rgba(161, 124, 72, 0.16)',
      gap: Spacing.xs,
    },
    rewardText: {
      lineHeight: 18,
    },
    modalFooter: {
      flexDirection: 'row',
      gap: Spacing.sm,
      padding: Spacing.lg,
      borderTopWidth: 1,
      borderTopColor: 'rgba(163, 126, 76, 0.14)',
      backgroundColor: '#110d09',
    },
  });
