import { StyleSheet, Dimensions } from 'react-native';
import { Spacing, BorderRadius, Theme } from '@/constants/theme';

const { width } = Dimensions.get('window');

export const createStyles = (_theme: Theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#0a0706',
    },
    enemyInfoBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: Spacing.md,
      paddingVertical: 10,
      backgroundColor: '#140f0b',
      borderBottomWidth: 1,
      borderBottomColor: 'rgba(171, 128, 71, 0.24)',
      minHeight: 48,
    },
    enemyNameSection: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
    },
    enemyName: {
      letterSpacing: 1.2,
      fontWeight: '600',
    },
    enemyStats: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
    },
    statItemCompact: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    statTextCompact: {
      fontWeight: '700',
      fontSize: 13,
    },
    statDivider: {
      width: 1,
      height: 14,
      backgroundColor: 'rgba(210, 178, 123, 0.22)',
      marginHorizontal: 4,
    },
    rulesBar: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: Spacing.sm,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      backgroundColor: '#0f0b08',
      borderBottomWidth: 1,
      borderBottomColor: 'rgba(153, 118, 66, 0.14)',
    },
    ruleChip: {
      flexGrow: 1,
      minWidth: 145,
      paddingHorizontal: Spacing.sm,
      paddingVertical: Spacing.sm,
      borderRadius: BorderRadius.lg,
      backgroundColor: '#17110c',
      borderWidth: 1,
      borderColor: 'rgba(170, 130, 74, 0.18)',
      gap: 2,
    },
    ruleChipLabel: {
      letterSpacing: 1,
      textTransform: 'uppercase',
    },
    ruleChipValue: {
      lineHeight: 18,
    },
    battlefield: {
      flex: 1,
      paddingHorizontal: Spacing.md,
      paddingTop: Spacing.md,
      paddingBottom: Spacing.sm,
      gap: Spacing.sm,
      backgroundColor: '#0b0907',
    },
    battlefieldHeader: {
      gap: Spacing.xs,
      padding: Spacing.md,
      borderRadius: BorderRadius.xl,
      backgroundColor: '#15100c',
      borderWidth: 1,
      borderColor: 'rgba(167, 128, 73, 0.18)',
    },
    battlefieldFocusRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: Spacing.sm,
    },
    battlefieldLabel: {
      letterSpacing: 1,
      textTransform: 'uppercase',
    },
    targetBadge: {
      paddingHorizontal: Spacing.sm,
      paddingVertical: 4,
      borderRadius: BorderRadius.full,
      backgroundColor: '#8a482d',
      borderWidth: 1,
      borderColor: '#d8b16b',
    },
    targetBadgeText: {
      letterSpacing: 1,
      fontWeight: '700',
    },
    selectionText: {
      lineHeight: 20,
    },
    swipeHintRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: Spacing.xs,
    },
    swipeHint: {
      paddingHorizontal: Spacing.sm,
      paddingVertical: 4,
      borderRadius: BorderRadius.full,
      backgroundColor: '#0d0a08',
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: 'rgba(158, 122, 72, 0.14)',
    },
    slotRowBlock: {
      gap: Spacing.sm,
      padding: Spacing.sm,
      borderRadius: BorderRadius.xl,
      backgroundColor: '#110d0a',
      borderWidth: 1,
      borderColor: 'rgba(151, 118, 72, 0.14)',
    },
    rowHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    rowHeaderLabel: {
      letterSpacing: 1,
      fontWeight: '700',
    },
    rowHeaderHint: {
      lineHeight: 18,
      textAlign: 'right',
      flexShrink: 1,
    },
    slotRowGrid: {
      flexDirection: width < 480 ? 'column' : 'row',
      gap: Spacing.sm,
    },
    battleDivider: {
      height: 1,
      backgroundColor: 'rgba(145, 111, 66, 0.18)',
      marginVertical: Spacing.xs,
    },
    logPanel: {
      flexDirection: 'row',
      gap: Spacing.sm,
      paddingHorizontal: Spacing.md,
      paddingBottom: Spacing.sm,
      backgroundColor: '#0f0b08',
      flexWrap: 'wrap',
    },
    logItem: {
      flex: 1,
      minWidth: 180,
      flexDirection: 'row',
      gap: Spacing.sm,
      padding: Spacing.sm,
      borderRadius: BorderRadius.lg,
      backgroundColor: '#17110c',
      borderWidth: 1,
      borderColor: 'rgba(159, 122, 72, 0.16)',
    },
    logAccent: {
      width: 4,
      borderRadius: 999,
    },
    logCopy: {
      flex: 1,
      gap: 2,
    },
    logDetail: {
      lineHeight: 18,
    },
    handContainer: {
      borderTopWidth: 1,
      borderTopColor: 'rgba(164, 127, 76, 0.16)',
      paddingVertical: Spacing.xs,
      backgroundColor: '#120d09',
      height: 292,
    },
    handInfoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: Spacing.md,
      marginBottom: 4,
    },
    handLabel: {
      letterSpacing: 1,
      fontWeight: '600',
    },
    handFanContainer: {
      position: 'relative',
      width: '100%',
      height: 232,
      alignItems: 'center',
      justifyContent: 'flex-end',
      paddingBottom: 0,
    },
    actionBar: {
      flexDirection: 'row',
      gap: Spacing.sm,
      padding: Spacing.md,
      paddingTop: Spacing.sm,
      backgroundColor: '#0c0907',
      minHeight: 56,
      alignItems: 'center',
      justifyContent: 'space-between',
      borderTopWidth: 1,
      borderTopColor: 'rgba(150, 118, 70, 0.14)',
    },
    actionButtonSecondary: {
      paddingVertical: Spacing.sm,
      paddingHorizontal: Spacing.md,
      borderWidth: 1,
      borderColor: '#7f6542',
      borderRadius: BorderRadius.md,
      flexDirection: 'row',
      gap: Spacing.xs,
      alignItems: 'center',
      backgroundColor: '#15100c',
    },
    buttonTextSecondary: {
      fontWeight: '600',
    },
    playerStatsCompact: {
      flexDirection: 'column',
      alignItems: 'center',
      gap: Spacing.xs,
    },
    statRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
    },
    turnBadge: {
      backgroundColor: '#8b492d',
      paddingHorizontal: Spacing.sm,
      paddingVertical: 4,
      borderRadius: 2,
      borderWidth: 1,
      borderColor: '#d1a265',
    },
    turnText: {
      letterSpacing: 1,
      fontWeight: '700',
      fontSize: 11,
    },
    actionButtonPrimary: {
      paddingVertical: Spacing.sm,
      paddingHorizontal: Spacing.xl,
      backgroundColor: '#8f5234',
      borderWidth: 1,
      borderColor: '#d1a365',
      borderRadius: BorderRadius.md,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.24,
      shadowRadius: 18,
      elevation: 6,
    },
    buttonTextPrimary: {
      fontWeight: '700',
      letterSpacing: 0.5,
    },
  });
