import { StyleSheet } from 'react-native';
import { BorderRadius, Spacing, Theme } from '@/constants/theme';

export const createStyles = (_theme: Theme, width: number) =>
  StyleSheet.create({
    scrollContent: {
      flexGrow: 1,
      paddingBottom: width >= 1280 ? Spacing.xl : Spacing['5xl'],
      backgroundColor: '#0a0706',
      gap: Spacing.lg,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      gap: Spacing.md,
      backgroundColor: '#0a0706',
    },
    loadingText: {
      marginTop: Spacing.md,
    },
    heroSection: {
      overflow: 'hidden',
      paddingTop: width >= 1280 ? Spacing['2xl'] : Spacing['4xl'],
      paddingBottom: width >= 1280 ? Spacing.xl : Spacing['3xl'],
      paddingHorizontal: Spacing.xl,
      backgroundColor: '#130e0a',
      borderBottomWidth: 1,
      borderBottomColor: 'rgba(166, 129, 73, 0.22)',
      gap: Spacing.lg,
    },
    heroHalo: {
      position: 'absolute',
      top: -80,
      alignSelf: 'center',
      width: 280,
      height: 280,
      borderRadius: 999,
      backgroundColor: 'rgba(139, 74, 38, 0.18)',
    },
    heroSubtitle: {
      textTransform: 'uppercase',
      letterSpacing: 5,
      textAlign: 'center',
    },
    heroTitle: {
      textAlign: 'center',
      letterSpacing: 2,
      fontSize: width >= 1280 ? 34 : 42,
      fontWeight: '300',
    },
    heroCopy: {
      textAlign: 'center',
      lineHeight: 22,
      maxWidth: 480,
      alignSelf: 'center',
    },
    progressRow: {
      flexDirection: 'row',
      gap: Spacing.sm,
      flexWrap: 'wrap',
      justifyContent: 'center',
    },
    progressChip: {
      minWidth: 96,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      borderRadius: BorderRadius.xl,
      alignItems: 'center',
      backgroundColor: '#1a130e',
      borderWidth: 1,
      borderColor: 'rgba(170, 132, 77, 0.22)',
      gap: 2,
    },
    storyCard: {
      marginHorizontal: Spacing.lg,
      padding: Spacing.xl,
      borderRadius: BorderRadius['2xl'],
      backgroundColor: '#17110d',
      borderWidth: 1,
      borderColor: 'rgba(177, 138, 82, 0.26)',
      gap: Spacing.lg,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 16 },
      shadowOpacity: 0.26,
      shadowRadius: 24,
      elevation: 10,
    },
    desktopRow: {
      flexDirection: 'row',
      gap: Spacing.lg,
      paddingHorizontal: Spacing.lg,
    },
    desktopColumn: {
      flex: 1,
      minWidth: 0,
    },
    storyCardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.md,
    },
    storyYearBadge: {
      width: 64,
      height: 64,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#d7b26d',
    },
    storyTitleBlock: {
      flex: 1,
      gap: 4,
    },
    storyDescription: {
      lineHeight: 22,
    },
    storyBackground: {
      lineHeight: 20,
    },
    beatsGrid: {
      flexDirection: 'row',
      gap: Spacing.md,
      flexWrap: 'wrap',
    },
    beatCardWrap: {
      flex: 1,
      minWidth: 180,
      borderRadius: BorderRadius.xl,
    },
    beatCard: {
      padding: Spacing.md,
      borderRadius: BorderRadius.xl,
      backgroundColor: '#100c09',
      borderWidth: 1,
      borderColor: 'rgba(158, 123, 74, 0.16)',
      gap: Spacing.sm,
    },
    beatIcon: {
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#1e140e',
      borderWidth: 1,
      borderColor: 'rgba(179, 139, 81, 0.22)',
    },
    beatCopy: {
      lineHeight: 19,
    },
    ctaRow: {
      flexDirection: 'row',
      gap: Spacing.sm,
      flexWrap: 'wrap',
    },
    secondaryAction: {
      flex: 1,
      minWidth: 180,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: Spacing.xs,
      paddingVertical: Spacing.md,
      borderRadius: BorderRadius.full,
      backgroundColor: '#2a1d13',
      borderWidth: 1,
      borderColor: 'rgba(176, 137, 82, 0.24)',
    },
    primaryAction: {
      flex: 1,
      minWidth: 180,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: Spacing.xs,
      paddingVertical: Spacing.md,
      borderRadius: BorderRadius.full,
      backgroundColor: '#d7b26d',
      borderWidth: 1,
      borderColor: '#f1d39e',
    },
    chapterPreview: {
      marginHorizontal: width >= 1280 ? 0 : Spacing.lg,
      padding: Spacing.xl,
      borderRadius: BorderRadius['2xl'],
      backgroundColor: '#130f0c',
      borderWidth: 1,
      borderColor: 'rgba(166, 128, 74, 0.18)',
      gap: Spacing.md,
    },
    chapterPreviewHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: Spacing.md,
    },
    chapterTag: {
      paddingHorizontal: Spacing.sm,
      paddingVertical: 6,
      borderRadius: BorderRadius.full,
      backgroundColor: '#d7b26d',
    },
    chapterPreviewText: {
      lineHeight: 21,
    },
    chapterCarousel: {
      paddingTop: Spacing.xs,
    },
    chapterSlide: {
      gap: Spacing.md,
      paddingRight: width >= 1280 ? 0 : Spacing.lg,
    },
    chapterSlideFooter: {
      alignItems: 'flex-end',
    },
    chapterDots: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: Spacing.xs,
    },
    chapterDot: {
      width: 8,
      height: 8,
      borderRadius: 999,
      backgroundColor: 'rgba(143, 119, 89, 0.5)',
    },
    chapterDotActive: {
      width: 24,
      backgroundColor: '#d7b26d',
    },
    levelPreviewCard: {
      padding: Spacing.md,
      borderRadius: BorderRadius.xl,
      backgroundColor: '#0f0b08',
      borderWidth: 1,
      borderColor: 'rgba(158, 122, 73, 0.16)',
      gap: Spacing.sm,
    },
    levelPreviewHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: Spacing.md,
    },
    levelFactionBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: Spacing.sm,
      paddingVertical: 5,
      borderRadius: BorderRadius.full,
      backgroundColor: '#1b130d',
      borderWidth: 1,
      borderColor: 'rgba(176, 138, 82, 0.18)',
    },
    levelPreviewText: {
      lineHeight: 20,
    },
  });
