import { StyleSheet } from 'react-native';
import { BorderRadius, Spacing, Theme } from '@/constants/theme';

export const createStyles = (theme: Theme) => StyleSheet.create({
  page: { paddingHorizontal: Spacing.lg, paddingTop: Spacing.lg, paddingBottom: Spacing['5xl'], gap: Spacing.lg },
  headerCard: { borderRadius: BorderRadius['2xl'], padding: Spacing.lg, gap: Spacing.lg, borderWidth: 1, borderColor: theme.borderLight },
  headerRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md, flexWrap: 'wrap' },
  titleBlock: { flex: 1, minWidth: 180, gap: Spacing.xs },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, flexWrap: 'wrap', justifyContent: 'flex-end' },
  iconButton: { minWidth: 36, minHeight: 36, borderRadius: BorderRadius.full, borderWidth: 1, borderColor: theme.borderLight, alignItems: 'center', justifyContent: 'center', paddingHorizontal: Spacing.sm, paddingVertical: Spacing.sm, backgroundColor: theme.backgroundDefault, gap: Spacing.xs },
  primaryButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.xs, paddingHorizontal: Spacing.md, paddingVertical: Spacing.sm, borderRadius: BorderRadius.full },
  statsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm },
  statCard: { flexGrow: 1, minWidth: 120, padding: Spacing.md, borderRadius: BorderRadius.xl, borderWidth: 1, borderColor: theme.borderLight, gap: Spacing.xs },
  bodyGrid: { flexDirection: 'row', gap: Spacing.lg, alignItems: 'flex-start' },
  leftPane: { flex: 1.15, gap: Spacing.lg },
  rightPane: { flex: 0.85, gap: Spacing.lg },
  toolbarCard: { borderRadius: BorderRadius['2xl'], padding: Spacing.lg, borderWidth: 1, borderColor: theme.borderLight, gap: Spacing.md },
  searchInput: { borderWidth: 1, borderRadius: BorderRadius.full, paddingHorizontal: Spacing.lg, paddingVertical: Spacing.md, fontSize: 14 },
  filterRow: { gap: Spacing.sm, paddingVertical: Spacing.xs },
  chip: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs, borderWidth: 1, borderRadius: BorderRadius.full, paddingHorizontal: Spacing.md, paddingVertical: Spacing.sm },
  chipActive: {},
  toolbarFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: Spacing.md, flexWrap: 'wrap' },
  cardsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.md },
  cardTile: { width: '48.2%', minWidth: 240, borderRadius: BorderRadius['2xl'], borderWidth: 1, backgroundColor: theme.backgroundDefault, padding: Spacing.md, gap: Spacing.sm },
  cardTileActive: { shadowColor: theme.primary, shadowOpacity: 0.15, shadowRadius: 12, elevation: 2 },
  cardHead: { gap: 2 },
  cardBody: { borderRadius: BorderRadius.xl, borderWidth: 1, borderColor: theme.borderLight, padding: Spacing.md, gap: Spacing.sm, backgroundColor: theme.backgroundTertiary, minHeight: 100 },
  costBadge: { alignSelf: 'flex-start', borderWidth: 2, borderRadius: BorderRadius.full, paddingHorizontal: Spacing.sm, paddingVertical: 4, backgroundColor: theme.backgroundDefault },
  tileActions: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: Spacing.xs, flexWrap: 'wrap' },
  tileAction: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: Spacing.sm, paddingVertical: Spacing.xs, borderRadius: BorderRadius.full, backgroundColor: theme.backgroundTertiary },
  previewCard: { borderRadius: BorderRadius['2xl'], padding: Spacing.lg, borderWidth: 1, borderColor: theme.borderLight, gap: Spacing.md },
  previewHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: Spacing.sm },
  previewArtWrap: { borderRadius: BorderRadius['2xl'], overflow: 'hidden' },
  previewImage: { width: '100%', minHeight: 220, borderRadius: BorderRadius['2xl'], backgroundColor: theme.backgroundTertiary },
  previewPlaceholder: { alignItems: 'center', justifyContent: 'center', padding: Spacing.xl, borderWidth: 1, borderColor: theme.borderLight, borderRadius: BorderRadius['2xl'] },
  previewStats: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.md },
  previewStat: { padding: Spacing.md, borderRadius: BorderRadius.xl, backgroundColor: theme.backgroundTertiary, minWidth: 88, alignItems: 'center' },
  previewBattleStats: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm },
  battleStat: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs, paddingHorizontal: Spacing.md, paddingVertical: Spacing.sm, borderRadius: BorderRadius.full, backgroundColor: theme.backgroundTertiary },
  previewAbility: { borderRadius: BorderRadius.xl, padding: Spacing.md, gap: 4 },
  previewActions: { flexDirection: 'row', gap: Spacing.sm },
  previewAction: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.xs, paddingVertical: Spacing.md, borderRadius: BorderRadius.full },
  quickHint: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, borderRadius: BorderRadius.xl, padding: Spacing.md },
  emptyState: { flex: 1, minHeight: 260, alignItems: 'center', justifyContent: 'center', borderRadius: BorderRadius['2xl'], padding: Spacing.xl, gap: Spacing.sm, borderWidth: 1, borderColor: theme.borderLight },
  previewEmpty: { flex: 1, minHeight: 260, alignItems: 'center', justifyContent: 'center', borderRadius: BorderRadius['2xl'], padding: Spacing.xl, gap: Spacing.sm, borderWidth: 1, borderColor: theme.borderLight },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.5)', justifyContent: 'center', padding: Spacing.md },
  modalCard: { maxHeight: '92%', borderRadius: BorderRadius['2xl'], backgroundColor: theme.backgroundDefault, overflow: 'hidden' },
  modalHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: Spacing.sm, padding: Spacing.lg, borderBottomWidth: 1, borderBottomColor: theme.borderLight },
  modalContent: { padding: Spacing.lg, gap: Spacing.lg },
  formSection: { gap: Spacing.md },
  fieldRow: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.md },
  fieldHalf: { flex: 1, minWidth: 220, gap: Spacing.xs },
  fieldInput: { borderWidth: 1, borderRadius: BorderRadius.lg, paddingHorizontal: Spacing.md, paddingVertical: Spacing.sm, minHeight: 44 },
  fieldTextarea: { borderWidth: 1, borderRadius: BorderRadius.lg, paddingHorizontal: Spacing.md, paddingVertical: Spacing.md, minHeight: 100, textAlignVertical: 'top' },
  selectorRow: { gap: Spacing.sm, paddingVertical: Spacing.xs },
  selectorChip: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs, borderWidth: 1, borderRadius: BorderRadius.full, paddingHorizontal: Spacing.md, paddingVertical: Spacing.sm },
  selectorChipActive: {},
  abilityRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  abilityInput: { flex: 1, borderWidth: 1, borderRadius: BorderRadius.lg, paddingHorizontal: Spacing.md, paddingVertical: Spacing.sm },
  abilityDelete: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center', borderRadius: BorderRadius.lg, backgroundColor: theme.backgroundTertiary },
  addRowButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.xs, borderWidth: 1, borderRadius: BorderRadius.lg, paddingVertical: Spacing.sm },
  footerButton: { minHeight: 44, paddingHorizontal: Spacing.lg, borderRadius: BorderRadius.full, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.xs },
  footerGhostButton: { backgroundColor: theme.backgroundTertiary },
  footerPrimaryButton: {},
  modalFooter: { flexDirection: 'row', justifyContent: 'flex-end', gap: Spacing.sm, padding: Spacing.lg, borderTopWidth: 1, borderTopColor: theme.borderLight, flexWrap: 'wrap' },
  longInput: { minHeight: 260, borderWidth: 1, borderRadius: BorderRadius.lg, paddingHorizontal: Spacing.md, paddingVertical: Spacing.md, textAlignVertical: 'top' },
});
