import { StyleSheet } from 'react-native';
import { BorderRadius, Spacing, Theme } from '@/constants/theme';

export const createStyles = (_theme: Theme, width: number, height: number) =>
  StyleSheet.create({
    page: {
      flexGrow: 1,
      paddingHorizontal: Spacing.lg,
      paddingTop: Spacing.lg,
      paddingBottom: width >= 1360 ? Spacing.lg : Spacing['5xl'],
      gap: Spacing.lg,
      backgroundColor: '#0c0907',
    },
    headerCard: {
      borderRadius: BorderRadius['2xl'],
      padding: Spacing.lg,
      gap: Spacing.lg,
      borderWidth: 1,
      borderColor: 'rgba(170, 133, 82, 0.28)',
      backgroundColor: '#17110d',
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 18 },
      shadowOpacity: 0.28,
      shadowRadius: 30,
      elevation: 12,
    },
    headerRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md, flexWrap: 'wrap' },
    titleBlock: { flex: 1, minWidth: 180, gap: Spacing.xs },
    headerActions: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, flexWrap: 'wrap', justifyContent: 'flex-end' },
    iconButton: {
      minWidth: 38,
      minHeight: 38,
      borderRadius: BorderRadius.full,
      borderWidth: 1,
      borderColor: 'rgba(164, 129, 78, 0.34)',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: Spacing.sm,
      paddingVertical: Spacing.sm,
      backgroundColor: '#0f0b08',
      gap: Spacing.xs,
    },
    primaryButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: Spacing.xs,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      borderRadius: BorderRadius.full,
      backgroundColor: '#8f5234',
    },
    statsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm },
    statCard: {
      flexGrow: 1,
      minWidth: 120,
      padding: Spacing.md,
      borderRadius: BorderRadius.xl,
      borderWidth: 1,
      borderColor: 'rgba(163, 128, 80, 0.24)',
      gap: Spacing.xs,
      backgroundColor: '#100c09',
    },
    bodyGrid: {
      flexDirection: width >= 1360 ? 'row' : 'column',
      gap: Spacing.lg,
      alignItems: 'flex-start',
      minHeight: width >= 1360 ? height - 240 : undefined,
    },
    leftPane: {
      flex: 1.15,
      gap: Spacing.lg,
      width: width >= 1360 ? undefined : '100%',
    },
    rightPane: {
      flex: 0.85,
      gap: Spacing.lg,
      width: width >= 1360 ? undefined : '100%',
    },
    toolbarCard: {
      borderRadius: BorderRadius['2xl'],
      padding: Spacing.lg,
      borderWidth: 1,
      borderColor: 'rgba(160, 123, 72, 0.22)',
      gap: Spacing.md,
      backgroundColor: '#15100c',
    },
    searchInput: {
      borderWidth: 1,
      borderRadius: BorderRadius.full,
      paddingHorizontal: Spacing.lg,
      paddingVertical: Spacing.md,
      fontSize: 14,
      backgroundColor: '#0d0a08',
    },
    filterRow: { gap: Spacing.sm, paddingVertical: Spacing.xs },
    chip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
      borderWidth: 1,
      borderRadius: BorderRadius.full,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      backgroundColor: '#100c09',
      borderColor: 'rgba(140, 111, 69, 0.24)',
    },
    chipActive: {},
    toolbarFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: Spacing.md, flexWrap: 'wrap' },
    cardsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: Spacing.md,
      maxHeight: width >= 1360 ? Math.max(320, height - 380) : undefined,
      overflow: 'hidden',
    },
    cardTile: { width: width >= 1600 ? '31.8%' : '48.2%', minWidth: width >= 1360 ? 260 : 240, gap: Spacing.sm },
    cardTileSurface: { borderRadius: BorderRadius['3xl'] },
    cardTileFace: {
      aspectRatio: 5 / 7,
      borderRadius: BorderRadius['3xl'],
      borderWidth: 1,
      backgroundColor: '#1a130e',
      overflow: 'hidden',
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.26,
      shadowRadius: 22,
      elevation: 7,
    },
    cardTileBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: '#1a130e',
    },
    cardTileFaceContent: { flex: 1, padding: Spacing.sm, gap: Spacing.sm },
    cardTileTopBar: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: Spacing.xs },
    cardTileCostOrb: {
      width: 46,
      height: 46,
      borderRadius: 23,
      borderWidth: 2,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#efe0b7',
    },
    cardTileTopMeta: { flexDirection: 'row', flexWrap: 'wrap', gap: 4, justifyContent: 'flex-end' },
    cardTileArtwork: {
      flex: 1.1,
      minHeight: 0,
      borderRadius: BorderRadius['2xl'],
      borderWidth: 1,
      overflow: 'hidden',
      backgroundColor: '#2a2016',
    },
    cardTileArtworkImage: { width: '100%', height: '100%' },
    cardTileArtworkPlaceholder: { width: '100%', height: '100%', alignItems: 'center', justifyContent: 'center', padding: Spacing.sm },
    cardTileTypeRibbon: {
      position: 'absolute',
      left: Spacing.sm,
      bottom: Spacing.sm,
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
      paddingHorizontal: Spacing.sm,
      paddingVertical: 4,
      borderRadius: BorderRadius.full,
    },
    cardTileTitleBlock: { gap: 6 },
    cardTileTitle: { textAlign: 'center', letterSpacing: 0.3 },
    cardTileDescription: { lineHeight: 18 },
    cardTileStats: { flexDirection: 'row', flexWrap: 'wrap', gap: 4, justifyContent: 'center' },
    cardTileStatPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: Spacing.sm,
      paddingVertical: 4,
      borderRadius: BorderRadius.full,
      backgroundColor: '#0f0b08',
      borderWidth: 1,
      borderColor: 'rgba(158, 122, 75, 0.16)',
    },
    cardTileActive: { shadowColor: '#b98a45', shadowOpacity: 0.28, shadowRadius: 18, elevation: 8 },
    cardHead: { gap: 2 },
    cardBody: {
      borderRadius: BorderRadius.xl,
      borderWidth: 1,
      borderColor: 'rgba(173, 133, 82, 0.2)',
      padding: Spacing.md,
      gap: Spacing.sm,
      backgroundColor: '#100c09',
      minHeight: 100,
    },
    costBadge: {
      alignSelf: 'flex-start',
      borderWidth: 2,
      borderRadius: BorderRadius.full,
      paddingHorizontal: Spacing.sm,
      paddingVertical: 4,
      backgroundColor: '#f1dec3',
    },
    tileActions: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: Spacing.xs, flexWrap: 'wrap' },
    tileAction: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: Spacing.sm,
      paddingVertical: Spacing.xs,
      borderRadius: BorderRadius.full,
      backgroundColor: '#140f0b',
      borderWidth: 1,
      borderColor: 'rgba(167, 129, 77, 0.2)',
    },
    previewCard: {
      borderRadius: BorderRadius['2xl'],
      padding: Spacing.lg,
      borderWidth: 1,
      borderColor: 'rgba(180, 141, 85, 0.28)',
      gap: Spacing.md,
      backgroundColor: '#17110d',
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 20 },
      shadowOpacity: 0.3,
      shadowRadius: 30,
      elevation: 12,
      minHeight: width >= 1360 ? Math.max(420, height - 420) : undefined,
    },
    previewHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: Spacing.sm },
    previewArtWrap: { borderRadius: BorderRadius['2xl'], overflow: 'hidden' },
    previewImage: { width: '100%', minHeight: 220, borderRadius: BorderRadius['2xl'], backgroundColor: '#261d14' },
    previewPlaceholder: {
      alignItems: 'center',
      justifyContent: 'center',
      padding: Spacing.xl,
      borderWidth: 1,
      borderColor: 'rgba(165, 128, 76, 0.2)',
      borderRadius: BorderRadius['2xl'],
      backgroundColor: '#110d09',
    },
    previewStats: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.md },
    previewStat: {
      padding: Spacing.md,
      borderRadius: BorderRadius.xl,
      backgroundColor: '#0f0b08',
      minWidth: 88,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: 'rgba(154, 121, 74, 0.18)',
    },
    previewBattleStats: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm },
    battleStat: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      borderRadius: BorderRadius.full,
      backgroundColor: '#0d0a08',
      borderWidth: 1,
      borderColor: 'rgba(164, 128, 76, 0.16)',
    },
    previewAbility: { borderRadius: BorderRadius.xl, padding: Spacing.md, gap: 4 },
    previewActions: { flexDirection: 'row', gap: Spacing.sm, flexWrap: 'wrap' },
    previewAction: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.xs, paddingVertical: Spacing.md, borderRadius: BorderRadius.full },
    quickHint: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      borderRadius: BorderRadius.xl,
      padding: Spacing.md,
      backgroundColor: '#15100c',
      borderWidth: 1,
      borderColor: 'rgba(156, 123, 76, 0.2)',
    },
    emptyState: {
      flex: 1,
      minHeight: 260,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: BorderRadius['2xl'],
      padding: Spacing.xl,
      gap: Spacing.sm,
      borderWidth: 1,
      borderColor: 'rgba(170, 129, 78, 0.24)',
      backgroundColor: '#15100c',
    },
    previewEmpty: {
      flex: 1,
      minHeight: 260,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: BorderRadius['2xl'],
      padding: Spacing.xl,
      gap: Spacing.sm,
      borderWidth: 1,
      borderColor: 'rgba(173, 131, 79, 0.22)',
      backgroundColor: '#17110d',
    },
    cardFrame: {
      aspectRatio: 5 / 7,
      borderRadius: BorderRadius['4xl'],
      padding: Spacing.sm,
      borderWidth: 1,
      borderColor: 'rgba(181, 142, 85, 0.34)',
      overflow: 'hidden',
      backgroundColor: '#1c140e',
    },
    cardFlipStage: {
      flex: 1,
      position: 'relative',
    },
    cardFace: {
      ...StyleSheet.absoluteFillObject,
      backfaceVisibility: 'hidden',
    },
    cardFaceBack: {
      padding: Spacing.md,
      gap: Spacing.sm,
      justifyContent: 'space-between',
      backgroundColor: '#16100c',
    },
    cardBackdrop: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: '#221811',
    },
    cardRim: {
      position: 'absolute',
      top: Spacing.sm,
      left: Spacing.sm,
      right: Spacing.sm,
      bottom: Spacing.sm,
      borderWidth: 2,
      borderRadius: BorderRadius['4xl'],
      opacity: 0.8,
    },
    cardContent: { flex: 1, gap: Spacing.xs },
    cardTopBar: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: Spacing.sm },
    cardCostOrb: {
      width: 58,
      height: 58,
      borderRadius: 29,
      borderWidth: 2,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#efe0b8',
    },
    cardTopMeta: { flex: 1, flexDirection: 'row', justifyContent: 'flex-end', flexWrap: 'wrap', gap: Spacing.xs },
    cardArtwork: {
      flex: 1.15,
      minHeight: 0,
      borderWidth: 1,
      borderRadius: BorderRadius['3xl'],
      overflow: 'hidden',
      backgroundColor: '#2b2016',
    },
    cardArtworkImage: { width: '100%', height: '100%' },
    cardArtworkPlaceholder: { width: '100%', height: '100%', alignItems: 'center', justifyContent: 'center' },
    cardTypeRibbon: {
      position: 'absolute',
      left: Spacing.md,
      bottom: Spacing.md,
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
      paddingHorizontal: Spacing.md,
      paddingVertical: 6,
      borderRadius: BorderRadius.full,
    },
    cardTitleBlock: { gap: Spacing.xs, paddingHorizontal: Spacing.xs, paddingTop: Spacing.xs },
    cardTitle: { textAlign: 'center', letterSpacing: 0.5 },
    cardFlavorText: { fontStyle: 'italic' },
    cardStatGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.xs, justifyContent: 'center' },
    cardStatPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
      paddingHorizontal: Spacing.sm,
      paddingVertical: Spacing.xs,
      borderRadius: BorderRadius.full,
      backgroundColor: '#0f0b08',
      borderWidth: 1,
      borderColor: 'rgba(161, 122, 72, 0.16)',
    },
    cardAbilityBox: {
      borderRadius: BorderRadius.xl,
      padding: Spacing.sm,
      gap: 4,
      backgroundColor: '#0f0b08',
      borderWidth: 1,
      borderColor: 'rgba(166, 129, 74, 0.16)',
    },
    cardBackTop: {
      gap: Spacing.xs,
      paddingBottom: Spacing.sm,
      borderBottomWidth: 1,
      borderBottomColor: 'rgba(166, 129, 74, 0.18)',
    },
    cardBackSection: {
      borderRadius: BorderRadius.xl,
      padding: Spacing.md,
      gap: Spacing.xs,
      backgroundColor: '#0f0b08',
      borderWidth: 1,
      borderColor: 'rgba(166, 129, 74, 0.16)',
    },
    modalBackdrop: { flex: 1, backgroundColor: 'rgba(2, 1, 1, 0.76)', justifyContent: 'center', padding: Spacing.md },
    modalCard: {
      maxHeight: width >= 1360 ? '88%' : '92%',
      width: width >= 1360 ? '86%' : '100%',
      maxWidth: 1360,
      alignSelf: 'center',
      borderRadius: BorderRadius['2xl'],
      backgroundColor: '#15100c',
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: 'rgba(171, 133, 82, 0.26)',
    },
    modalHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: Spacing.sm,
      padding: Spacing.lg,
      borderBottomWidth: 1,
      borderBottomColor: 'rgba(164, 129, 77, 0.16)',
    },
    modalContent: { padding: Spacing.lg, gap: Spacing.lg },
    formSection: {
      gap: Spacing.md,
      paddingBottom: Spacing.md,
      borderBottomWidth: 1,
      borderBottomColor: 'rgba(161, 123, 75, 0.12)',
    },
    fieldRow: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.md },
    fieldHalf: { flex: 1, minWidth: 220, gap: Spacing.xs },
    fieldInput: {
      borderWidth: 1,
      borderRadius: BorderRadius.lg,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      minHeight: 44,
      backgroundColor: '#0d0a08',
      borderColor: 'rgba(157, 124, 76, 0.18)',
    },
    fieldTextarea: {
      borderWidth: 1,
      borderRadius: BorderRadius.lg,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.md,
      minHeight: 100,
      textAlignVertical: 'top',
      backgroundColor: '#0d0a08',
      borderColor: 'rgba(158, 124, 76, 0.18)',
    },
    selectorRow: { gap: Spacing.sm, paddingVertical: Spacing.xs },
    selectorChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
      borderWidth: 1,
      borderRadius: BorderRadius.full,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      backgroundColor: '#0f0b08',
      borderColor: 'rgba(157, 124, 76, 0.16)',
    },
    selectorChipActive: {},
    abilityRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
    abilityInput: {
      flex: 1,
      borderWidth: 1,
      borderRadius: BorderRadius.lg,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      backgroundColor: '#0d0a08',
      borderColor: 'rgba(158, 122, 72, 0.16)',
    },
    abilityDelete: {
      width: 42,
      height: 42,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: BorderRadius.lg,
      backgroundColor: '#100c09',
      borderWidth: 1,
      borderColor: 'rgba(145, 61, 49, 0.22)',
    },
    addRowButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: Spacing.xs,
      borderWidth: 1,
      borderRadius: BorderRadius.lg,
      paddingVertical: Spacing.sm,
      backgroundColor: '#100c09',
      borderColor: 'rgba(157, 122, 73, 0.16)',
    },
    footerButton: {
      minHeight: 44,
      paddingHorizontal: Spacing.lg,
      borderRadius: BorderRadius.full,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: Spacing.xs,
    },
    footerGhostButton: {
      backgroundColor: '#0e0a08',
      borderWidth: 1,
      borderColor: 'rgba(162, 128, 75, 0.18)',
    },
    footerPrimaryButton: {},
    modalFooter: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: Spacing.sm,
      padding: Spacing.lg,
      borderTopWidth: 1,
      borderTopColor: 'rgba(168, 133, 81, 0.14)',
      flexWrap: 'wrap',
      backgroundColor: '#110d09',
    },
    longInput: {
      minHeight: 260,
      borderWidth: 1,
      borderRadius: BorderRadius.lg,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.md,
      textAlignVertical: 'top',
      backgroundColor: '#0d0a08',
      borderColor: 'rgba(159, 124, 76, 0.18)',
    },
    templateCard: {
      borderRadius: BorderRadius['2xl'],
      padding: Spacing.lg,
      borderWidth: 1,
      borderColor: 'rgba(167, 131, 79, 0.2)',
      gap: Spacing.md,
      backgroundColor: '#100c09',
    },
    templateActions: { flexDirection: 'row', gap: Spacing.sm, flexWrap: 'wrap' },
  });
